appName: paymentservice
appImage: gcr.io/google-samples/microservices-demo/frontend
appVersion: v0.9.0
appReplicas: 1
containerPort: 50051
containerEnvVars:
- name: PORT
  value: "50051"
- name: DISABLE_PROFILER
  value: "1"


servicePort: 50051
