appName: productcatalogservice
appImage: gcr.io/google-samples/microservices-demo/productcatalogservice
appVersion: v0.9.0
appReplicas: 1
containerPort: 3550
containerEnvVars: 
- name: PORT
  value: "3550"
- name: DISABLE_PROFILER
  value: "1"


servicePort: 3550
